// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    AvgTempBar: typeof import('./src/components/AvgTempBar.vue')['default']
    'AvgTempBar copy': typeof import('./src/components/AvgTempBar copy.vue')['default']
    BeefCuts: typeof import('./src/components/BeefCuts.vue')['default']
    SpeedGraph: typeof import('./src/components/SpeedGraph.vue')['default']
    TempLine: typeof import('./src/components/TempLine.vue')['default']
    TextAnimation: typeof import('./src/components/TextAnimation.vue')['default']
    WeatherPie: typeof import('./src/components/WeatherPie.vue')['default']
    WindVector: typeof import('./src/components/WindVector.vue')['default']
  }
}

export {}
